Run two wallet APIs for demo purposes
EspressoSystems/cape pull request #988
Opened 2022-04-21 12:53 UTC by sveitser

Close #983

2022-04-21 14:57 UTC, philippecamacho requested changes
Left a couple of comments.
Also should not we update the README.md to explain the tester how to use the two different wallets?

2022-04-21 15:01 UTC, sveitser commented on bin/wallet-api-bob
> +export CAPE_WALLET_PORT=$CAPE_WALLET_PORT_ALICE
Yes you are right they are inverted. It should still work but I will fix it.

2022-04-21 15:08 UTC, sveitser commented
>  Also should not we update the README.md to explain the tester how to use the two different wallets?

Good idea. I added it to the cape-ui README https://github.com/EspressoSystems/cape-ui/pull/252/commits/2fa04fb1b97dbadf6683ca076948b0fd90f896f5

2022-04-22 01:16 UTC, philippecamacho commented
It works! I was able to spin up two wallets and send 17 native CAP assets from one to another.

![image](https://user-images.githubusercontent.com/7206973/164577449-287da2f5-bf57-49b2-be4d-1f545f731878.png)
![image](https://user-images.githubusercontent.com/7206973/164577472-9497dadd-7e76-49be-aeed-b84affcdec8d.png)

2022-04-22 01:16 UTC, philippecamacho approved these changes
LGTM

2022-04-22 01:16 UTC, merged

2022-04-22 22:15 UTC, smfang commented
@philippecamacho , @sveitser , thanks again for making this feature available!  I ran into  an error with running the `yarn demo`.   (And updated the .env file as  displayed below). I can follow up again next week. 

![image](https://user-images.githubusercontent.com/49532779/164802627-03fd36da-d8be-40e5-b184-920b41ba8bbd.png)